#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ data.values.registry.server or assert.fail("missing registry.server")
#@ data.values.registry.repository or assert.fail("missing registry.repository")

---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-to-url
spec:
  selector:
    apps.tanzu.vmware.com/workload-type: web

  serviceAccountRef:
    name: #@ data.values.service_account

  params:
    - name: registry
      default: #@ data.values.registry
    - name: cluster_builder
      default: #@ data.values.cluster_builder
    - name: service_account
      default: #@ data.values.service_account
    - name: git_implementation
      default: #@ data.values.git_implementation
    - name: git_secret
      default: ""

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: git-repository

    - name: source-tester
      templateRef:
        kind: ClusterSourceTemplate
        name: testing
      sources:
        - resource: source-provider
          name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - resource: source-tester
          name: source

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app
      images:
        - resource: image-builder
          name: image
