---
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: hello-world
spec:
  #! name the images built after this
  #!
  tag: 10.188.0.3:5000/test/hello-world

  #! use the default builder that i've got (e.g., configured w/ golang
  #! buildpacks support)
  #!
  builder:
    kind: ClusterBuilder
    name: default

  #! build based on source code from here
  #!
  source:
    git:
      url: https://github.com/carto-run/hello-world
      revision: 979495ac3ce27d83d48de7d8db1cab46fa77388f
