---
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: hello-world
spec:
  tag: 10.188.0.3:5000/test/hello-world
  builder:
    kind: ClusterBuilder
    name: default
  source:
    git:
      url: https://github.com/carto-run/hello-world
      revision: 979495ac3ce27d83d48de7d8db1cab46fa77388f
